name: Pull Request Labeled

on:
  pull_request_target:
    types: [labeled]

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
  invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Reply to Pull Request
        uses: peter-evans/create-or-update-comment@v3
        if: "${{ github.event.label.name == 'Resolution: Invalid'}}"
        with:
          issue-number: ${{ github.event.number }}
          body: |
            We are happy to see you're contributing to fastjs, but we are unable to merge this pull request for now, because of:
            - This pull request does not fix a bug.
            - This pull request need to have some changes.
            - This pull request doesn't have a valid issue.
            - You did not follow our [Contributing Guidelines](https://docs.fastjs.cc/other/contributing.html).
            - This pull request violates our [Code of Conduct](https://docs.fastjs.cc/other/code-of-conduct.html).
            - Other reasons.

      - name: Close Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const label = context.payload.label;
            if (label.name === 'Resolution: Invalid') {
              github.rest.pulls.update({
                pull_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
            }

  deploy-test:
    runs-on: ubuntu-latest
    if: "${{ github.event.label.name == 'Resolution: Deploy Test'}}"
    steps:
      - name: Reply to Pull Request
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Your pull request sounds good, but we need to deploy this pull request to our test environment to make sure it works well.
            
            It will **automatically start**, please wait patiently.

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Test Environment
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          dist: 'dist'
          teardown: 'true'
          build: |
            npm install
            npm run build